apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  labels:
    type: local
    app: db-postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/database"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-claim
  labels:
    app: db-postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi