version: '3'

services:
  backend:
    image: example-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/logs.txt:/srv/app/backend/logs.txt
    environment:
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=salasana
      - DB_NAME=testi
      - DB_HOST=db
    container_name: backend
  frontend:
    image: example-frontend
    ports:
      - 5000:5000
    container_name: frontend
    environment:
      - API_URL=http://localhost/api
  redis:
    image: redis
    ports:
      - 6379:6379
    container_name: redis
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: salasana
      POSTGRES_DB: testi
    container_name: db
    volumes:
      - ./database:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - 80:80
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/run/docker.sock:/tmp/docker.sock:ro
