version: '3'

services:
  backend:
    image: example-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/logs.txt:/srv/app/backend/logs.txt
  frontend:
    image: example-frontend    
    ports:
      - 5000:5000

