version: '3'

services:
  backend:
    image: example-backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/logs.txt:/srv/app/backend/logs.txt
    environment:
      - REDIS=redis
  frontend:
    image: example-frontend    
    ports:
      - 5000:5000
  redis:
    image: redis
    ports:
      - 6379:6379
